In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
cvs = pd.read_csv(r'C:\Users\arun kumar\Desktop\figma+HACKATHONS\Coronavirus-Probability-Checker\Coronavirus-Probability-Checker-master\dataset.csv')
cvs.head(5)

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
0   99.254765         1   85          1           1              1
1   98.954284         0   55          0          -1              0
2  101.647720         0   84          0           0              1
3  101.318212         1   12          0           1              1
4   99.139178         1   24          0           0              0

In [3]:
cvs.describe()

fever     bodyPain          age    runnyNose   diffBreath  \
count  2889.000000  2889.000000  2889.000000  2889.000000  2889.000000   
mean     99.999273     0.510903    49.899965     0.491866    -0.027345   
std       1.134316     0.499968    28.847724     0.500020     0.826508   
min      98.000300     0.000000     1.000000     0.000000    -1.000000   
25%      99.036548     0.000000    25.000000     0.000000    -1.000000   
50%      99.993046     1.000000    49.000000     0.000000     0.000000   
75%     100.962298     1.000000    74.000000     1.000000     1.000000   
max     101.992313     1.000000   100.000000     1.000000     1.000000   

       infectionProb  
count    2889.000000  
mean        0.500519  
std         0.500086  
min         0.000000  
25%         0.000000  
50%         1.000000  
75%         1.000000  
max         1.000000

In [16]:
cvs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2889 entries, 0 to 2888
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   fever          2889 non-null   float64
 1   bodyPain       2889 non-null   int64  
 2   age            2889 non-null   int64  
 3   runnyNose      2889 non-null   int64  
 4   diffBreath     2889 non-null   int64  
 5   infectionProb  2889 non-null   int64  
dtypes: float64(1), int64(5)
memory usage: 135.5 KB


In [17]:
cvs.isnull()

fever  bodyPain    age  runnyNose  diffBreath  infectionProb
0     False     False  False      False       False          False
1     False     False  False      False       False          False
2     False     False  False      False       False          False
3     False     False  False      False       False          False
4     False     False  False      False       False          False
...     ...       ...    ...        ...         ...            ...
2884  False     False  False      False       False          False
2885  False     False  False      False       False          False
2886  False     False  False      False       False          False
2887  False     False  False      False       False          False
2888  False     False  False      False       False          False

[2889 rows x 6 columns]

Train_test_split

In [5]:
from sklearn.model_selection import train_test_split

X = cvs.drop('infectionProb', 1)
y = cvs['infectionProb']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Linear Regression

In [20]:
from sklearn.linear_model import LinearRegression

lin = LinearRegression()

lin.fit(X_train, y_train)

prediction = lin.predict(X_test)

In [21]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

abs_err = mean_absolute_error(y_test, prediction)
squ_err = mean_squared_error(y_test, prediction)

print("mean absolute error: ", (abs_err))
print("mean squared error: ", (squ_err))
print("root mean squared error: ", (np.sqrt(squ_err)))
print("Score: ", (r2_score(y_test, prediction)))

mean absolute error:  0.5005795530855176
mean squared error:  0.2507596168529061
root mean squared error:  0.5007590407101065
Score:  -0.003230654891159368


In [22]:
prediction.round()

array([1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1.,
       0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0.,
       1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1.,
       1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1., 0., 1., 0.,
       0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1.,
       0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 1., 0.

predicting new points

In [23]:
X_new = np.array([[104.344456, 1, 78, -1, 0],
                  [91.6587345, 0, 45, 0, 0],
                  [89.8738, 0, 45, 0, -1],
                  [90.10218, 1, 85, 0, -1],
                  [74.345, 0, 85, 0, 1],
                  [94.647, 1, 35, 0, 0],
                  [89.563, 1, 86, 1, 1],
                  [90.85635, 1, 42, 0, -1]])

In [24]:
X_new.shape

(8, 5)

In [25]:
regr = LinearRegression()

regr.fit(X_train, y_train)

new_pred = regr.predict(X_new)

In [26]:
new_pred.round()

array([0., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
X_test.columns

Index(['fever', 'bodyPain', 'age', 'runnyNose', 'diffBreath'], dtype='object')

# KNN Classifier appoach

In [28]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=8)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [29]:
val = np.array([[97, 0, 45, 0, -1]])

pred = lin.predict(val)

In [30]:
pred.round()

array([1.])

In [31]:
from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred)

print("", (report))

               precision    recall  f1-score   support

           0       0.49      0.62      0.55       293
           1       0.46      0.34      0.39       285

    accuracy                           0.48       578
   macro avg       0.48      0.48      0.47       578
weighted avg       0.48      0.48      0.47       578



In [ ]:
CONFUSION MATRIX-           actual values-
                             (1)      (0)
                        (1)   TP      FP
            pred values-(0)   TN      FN


In [32]:
from sklearn.metrics import confusion_matrix

matrix = confusion_matrix(y_test, y_pred)

print("", (matrix))

 [[181 112]
 [188  97]]
